AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Metrics/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
