AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'public/uploads/**/**/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AlignHash:
  Enabled: false
